// Vendored from https://github.com/martinopedal/alz-graph-queries/blob/8a3fddabcbf272a19a627770a0d33de5f4ace8ee/queries/alz_additional_queries.json
// Source checklist ID: 667313b4-f566-44b5-b984-a859c773e7d2
// Vendored at: 2026-04-22T12:35:39Z
resourcecontainers | where type == 'microsoft.management/managementgroups' | extend displayName = coalesce(tostring(properties.displayName), name), displayNameLower = tolower(displayName) | extend compliant = iff(displayNameLower has 'sandbox', 1, 0) | project name = displayName, id, compliant
