// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 088137f5-e6c4-4cfd-9e50-4547c2447ec6
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/virtualnetworks' | extend ddosPlanId = tostring(properties.ddosProtectionPlan.id), ddosEnabled = properties.enableDdosProtection | extend compliant = iff(ddosEnabled == true or isnotempty(ddosPlanId), 1, 0) | project name, id, compliant
