// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 0c47f486-656d-4699-8c30-edef5b8a93c4
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/publicipaddresses' | extend skuName=tostring(sku.name) | extend zoneInfo=tostring(zones) | extend compliant = iff(skuName =~ 'Standard', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Standard Public IP', currentValue=strcat('SKU: ', skuName, ', Zones: ', iff(isnotempty(zoneInfo), zoneInfo, 'None')), expectedValue='Standard, Zone-redundant', compliant
