// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 0d83fd81-952c-4d47-a6cb-3a930925ef2e
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.storage/storageaccounts' | extend replication=tostring(sku.name) | extend compliant = iff(replication has 'ZRS' or replication has 'GRS' or replication has 'GZRS' or replication has 'RAGRS' or replication has 'RAGZRS', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Storage Redundancy', currentValue=replication, expectedValue='ZRS/GRS/GZRS/RA-*', compliant
