// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 0dd4e625-9c4b-4a56-b54a-4357bac12761
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.aad/domainservices' | extend replicaCount=array_length(properties.replicaSets) | extend compliant = iff(replicaCount >= 2, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Entra DS Replicas', currentValue=strcat(tostring(replicaCount), ' set(s)'), expectedValue='2+', compliant
