// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 0e7c28ec-9366-4572-83b0-f4664b1d944a
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand peering=properties.virtualNetworkPeerings | summarize spokeCount=count() by id, name, resourceGroup, subscriptionId, location | project id, name, resourceGroup, subscriptionId, checkItem='Hub Spoke Count', currentValue=strcat(tostring(spokeCount), ' peerings in ', location), expectedValue='Add hub if >400 spokes', compliant=iff(spokeCount <= 400, true, false)
