// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 11deb39d-8299-4e47-bbe0-0fb5a36318a8
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/networksecuritygroups' | mv-expand rule=properties.securityRules | where rule.properties.direction =~ 'Inbound' and rule.properties.sourceAddressPrefix =~ 'VirtualNetwork' | project id, name, resourceGroup, subscriptionId, ruleName=tostring(rule.name), checkItem='NSG VirtualNetwork Tag', currentValue=strcat('Rule: ', tostring(rule.name), ' uses VirtualNetwork tag'), expectedValue='Avoid default VirtualNetwork tag reliance', compliant=false
