// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 14d99880-2f88-47e8-a134-62a7d85c94af
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/firewallpolicies' | extend dnsProxyEnabled = tostring(properties.dnsSettings.enableProxy) | extend compliant = iff(dnsProxyEnabled =~ 'true', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='DNS Proxy Enabled', currentValue=iff(isnotempty(dnsProxyEnabled), dnsProxyEnabled, 'Not configured'), expectedValue='true', compliant
