// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 153e8908-ae28-4c84-a33b-6b7808b9fe5c
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/privatednszones' | extend compliant = iff(indexof(name, '.') > 0, 1, 0) | project name, id, compliant
