// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 1559ab91-53e8-4908-ae28-c84c33b6b780
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.compute/virtualmachines' | where tolower(name) contains 'dc' or tolower(name) contains 'adds' | extend zoneCount=array_length(zones) | extend compliant = iff(zoneCount >= 1, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='DC in AZ', currentValue=iff(zoneCount > 0, tostring(zones), 'No AZ'), expectedValue='Availability Zone', compliant
