// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 15833ee7-ad6c-46d3-9331-65c7acbe44ab
// Vendored at: 2026-05-13T09:27:15+00:00
securityresources | where type == 'microsoft.security/assessments' | extend assessmentName = tostring(properties.displayName), statusCode = tostring(properties.status.code) | where assessmentName has 'system updates should be installed' or assessmentName has 'missing system updates' | extend compliant = iff(statusCode == 'Healthy', 1, 0) | project name, id, assessmentName, compliant
