// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 19048384-5c98-46cb-8913-156a12476e49
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend scope = tolower(tostring(properties.scope)) | where scope has '/providers/microsoft.management/managementgroups/' | summarize assignmentCount = count() | extend compliant = iff(assignmentCount <= 10, 1, 0) | project assignmentCount, compliant
