// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 1d7aa9b6-4704-4489-a804-2d88e79d17b7
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize frontDoors = countif(type == 'microsoft.cdn/profiles' and tostring(sku.name) has 'FrontDoor'), wafPolicies = countif(type in~ ('microsoft.cdn/cdnwebapplicationfirewallpolicies','microsoft.network/frontdoorwebapplicationfirewallpolicies')) | extend compliant = iff(frontDoors > 0 and wafPolicies > 0, 1, 0) | project frontDoors, wafPolicies, compliant
