// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 22d6419e-b627-4d95-9e7d-019fa759387f
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand subnets=properties.subnets | where subnets.name == 'AzureFirewallSubnet' | extend prefix=tostring(subnets.properties.addressPrefix) | extend prefixLen=toint(split(prefix, '/')[1]) | extend compliant = iff(prefixLen == 26, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='FW Subnet /26', currentValue=prefix, expectedValue='/26', compliant
