// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 2447ec66-138a-4720-8f1c-e16ed301d6e8
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworkgateways' | where properties.gatewayType =~ 'ExpressRoute' | extend skuName=tostring(properties.sku.name) | extend compliant = iff(skuName has 'AZ', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Zone-Redundant ER GW', currentValue=skuName, expectedValue='ErGw*AZ', compliant
