// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 2586b854-237e-47f1-84a1-d45d4cd2310d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/virtualhubs/hubvirtualnetworkconnections' | extend labels = properties.routingConfiguration.propagatedRouteTables.labels | extend compliant = iff(toint(coalesce(array_length(labels), 0)) > 0, 1, 0) | project name, id, compliant
