// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 261623a7-65a9-417e-8f34-8ef254c27d42
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualwans' | project id, name, resourceGroup, subscriptionId, checkItem='VWAN Deployed', currentValue=name, expectedValue='VWAN with Monitor Insights', compliant=true
