// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 2ba52752-6944-4008-ae7d-7e4843276d8b
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.keyvault/vaults' | extend softDelete = properties.enableSoftDelete, purgeProtection = properties.enablePurgeProtection | extend compliant = iff(softDelete == true and purgeProtection == true, 1, 0) | project name, id, compliant
