// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 2dd69c5b-5c26-422f-94b6-9bad33aad5e8
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | extend state = tostring(properties.state) | project id, name, subscriptionId, checkItem='Subscription State', currentValue=strcat(name, ': ', state), expectedValue='Active, quotas monitored', compliant=iff(state =~ 'Enabled', true, false)
