// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 2df27ee4-12e7-4f98-9f63-04722dd69c5b
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | extend mgChain=properties.managementGroupAncestorsChain | extend mgDepth=array_length(mgChain) | project id, name, subscriptionId, checkItem='MG Depth', currentValue=strcat(tostring(mgDepth), ' levels'), expectedValue='Max 4 levels', compliant=iff(mgDepth <= 4, true, false)
