// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 31e77d70-f001-455b-93aa-6d05eea10968
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend displayName = tolower(tostring(properties.displayName)), definitionId = tolower(tostring(properties.policyDefinitionId)) | extend compliant = iff(displayName has 'tls' or displayName has 'minimum tls' or definitionId has 'tls' or definitionId has 'minimumtlsversion', 1, 0) | project name, id, compliant
