// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 33b6b780-8b9f-4e5c-9104-9d403a923c34
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | extend mgParent=tostring(properties.managementGroupAncestorsChain[0].name) | extend isUnderRoot = iff(array_length(properties.managementGroupAncestorsChain) <= 1, true, false) | where isUnderRoot == true | project id, name, subscriptionId, checkItem='Sub Under Root MG', currentValue=strcat('Direct parent: ', mgParent), expectedValue='Not under Root MG', compliant=false
