// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 348ef254-c27d-442e-abba-c7571559ab91
// Vendored at: 2026-04-22T12:35:39Z
authorizationresources | where type =~ 'microsoft.authorization/roleassignments' | extend scope = tostring(properties.scope) | extend roleId = tostring(properties.roleDefinitionId) | extend principalType = tostring(properties.principalType) | summarize assignmentCount=count() by scope, principalType | project checkItem='RBAC Assignments by Scope', currentValue=strcat(principalType, ': ', tostring(assignmentCount), ' at ', scope), expectedValue='Aligned to cloud operating model', compliant=true
