// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 359c373e-7dd6-4162-9a36-4a907ecae48e
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize expressRouteCircuits = countif(type == 'microsoft.network/expressroutecircuits'), vpnGateways = countif(type == 'microsoft.network/virtualnetworkgateways' and tolower(tostring(properties.gatewayType)) == 'vpn') | extend compliant = iff(expressRouteCircuits > 0 and vpnGateways > 0, 1, 0) | project expressRouteCircuits, vpnGateways, compliant
