// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 373f482f-3e39-4d39-8aa4-7e566f6082b6
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/applicationgateways' or type =~ 'microsoft.cdn/profiles' or type =~ 'microsoft.network/frontdoors' | project id, name, resourceGroup, subscriptionId, type, checkItem='App Delivery Services', currentValue=strcat(type, ': ', name), expectedValue='WAF-enabled app delivery', compliant=true
