// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3829e7e3-1618-4368-9a04-77a209945bda
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend scope = tolower(tostring(properties.scope)) | extend compliant = iff(scope has '/providers/microsoft.management/managementgroups/', 1, 0) | project name, id, scope, compliant
