// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3a923c34-74d0-4001-aac6-a9e01e6a83de
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | where name has 'identity' or name has 'iam' or name has 'adds' | project id, name, subscriptionId, checkItem='Identity Subscription', currentValue=name, expectedValue='Dedicated identity subscription', compliant=true
