// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3d457936-e9b7-41eb-bdff-314b26450b12
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/routetables' | extend routeCount=array_length(properties.routes) | extend compliant = iff(routeCount <= 400, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Route Count', currentValue=strcat(tostring(routeCount), ' routes'), expectedValue='Max 400', compliant
