// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3f630472-2dd6-49c5-a5c2-622f54b69bad
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand addr=properties.addressSpace.addressPrefixes | extend prefix=tostring(addr) | extend isRFC1918 = iff(prefix startswith '10.' or prefix startswith '172.16.' or prefix startswith '192.168.', true, false) | extend compliant = isRFC1918 | project id, name, resourceGroup, subscriptionId, checkItem='RFC1918 Address', currentValue=prefix, expectedValue='RFC1918 range', compliant
