// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3f79ed00-203b-4c95-9efd-691505f5a1f9
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize diagnosticSettings = countif(type == 'microsoft.insights/diagnosticsettings' and tolower(id) has '/microsoft.network/virtualnetworkgateways/'), alerts = countif(type == 'microsoft.insights/metricalerts' and tolower(tostring(properties.scopes)) has 'microsoft.network/virtualnetworkgateways') | extend compliant = iff(diagnosticSettings > 0 or alerts > 0, 1, 0) | project diagnosticSettings, alerts, compliant
