// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 3f988795-25d6-4268-a6d7-0ba6c97be995
// Vendored at: 2026-05-13T09:27:15+00:00
authorizationresources | where type == 'microsoft.authorization/roleassignments' | extend roleDefinitionName = tostring(properties.roleDefinitionName) | extend compliant = iff(roleDefinitionName == 'Resource Policy Contributor', 1, 0) | project name, id, compliant
