// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 4722d929-c1b1-4cd6-81f5-4b29bade39ad
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize networkWatchers = countif(type == 'microsoft.network/networkwatchers'), connectionMonitors = countif(type in~ ('microsoft.network/networkwatchers/connectionmonitors','microsoft.network/connectionmonitors')) | extend compliant = iff(networkWatchers > 0 and connectionMonitors > 0, 1, 0) | project networkWatchers, connectionMonitors, compliant
