// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 48682fb1-1e86-4458-a686-518ebd47393d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/loadbalancers' | mv-expand pool=properties.backendAddressPools | extend backendCount=array_length(pool.properties.loadBalancerBackendAddresses) | extend compliant = iff(backendCount >= 2, true, false) | project id, name, resourceGroup, subscriptionId, poolName=tostring(pool.name), checkItem='LB Backend Size', currentValue=strcat(tostring(backendCount), ' instance(s)'), expectedValue='2+', compliant
