// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 49b82111-2df2-47ee-912e-7f983f630472
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type =~ 'microsoft.authorization/policyassignments' | summarize policyCount=count() | project checkItem='Policy Assignment Count', currentValue=strcat(tostring(policyCount), ' policy assignments'), expectedValue='Policies enforce ownership and tagging', compliant=iff(policyCount > 0, true, false)
