// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 4c27d42e-8bba-4c75-9155-9ab9153e8908
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize resourceCount=count() by type, location | project checkItem='Resource Region Distribution', resourceType=type, location, currentValue=strcat(type, ': ', tostring(resourceCount), ' in ', location), expectedValue='Resources in required regions', compliant=true
