// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 4d873974-8b66-42d6-b15f-512a65498f6d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworkgateways' | where properties.gatewayType =~ 'Vpn' | extend skuName=tostring(properties.sku.name) | extend compliant = iff(skuName has 'AZ', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Zone-Redundant VPN GW', currentValue=skuName, expectedValue='VpnGw*AZ', compliant
