// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 54b69bad-33aa-4d5e-ac68-e1d76667313b
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/virtualhubs' | summarize hubCount = count(), regionCount = dcount(location), regions = make_set(location) | extend compliant = iff(hubCount == regionCount and hubCount > 0, 1, 0) | project hubCount, regionCount, regions, compliant
