// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 54f0d8b1-22a3-4c0d-8ce2-58b9e086c93a
// Vendored at: 2026-04-22T12:35:39Z
resources | where type =~ 'microsoft.consumption/budgets' | extend amount = tostring(properties.amount) | extend timeGrain = tostring(properties.timeGrain) | project id, name, resourceGroup, subscriptionId, checkItem='Budget', currentValue=strcat('Amount: ', amount, ', Grain: ', timeGrain), expectedValue='Budget with alerts', compliant=true
