// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 5a4b1511-e43a-458a-ac22-99c4d7b57d0c
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/azurefirewalls' | extend firewallPolicyId = tostring(properties.firewallPolicy.id) | extend compliant = iff(isnotempty(firewallPolicyId), 1, 0) | project name, id, compliant
