// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 5cf9f485-2784-49b3-9824-75d9b8bdb57b
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | extend spendingLimit = tostring(properties.subscriptionPolicies.spendingLimit) | extend quotaId = tostring(properties.subscriptionPolicies.quotaId) | where quotaId has 'DevTest' or name has 'dev' or name has 'test' | project id, name, subscriptionId, checkItem='Dev/Test Subscriptions', currentValue=strcat(name, ' (', quotaId, ')'), expectedValue='Dev/Test offer for non-production', compliant=true
