// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 5e6c4cfd-3e50-4454-9c24-47ec66138a72
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.operationalinsights/workspaces' | extend retention = toint(properties.retentionInDays) | extend dataExport = properties.features.enableDataExport | extend compliant = iff(retention >= 365, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Log Retention', currentValue=strcat('Retention: ', tostring(retention), ' days'), expectedValue='365+ days or export to storage', compliant
