// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 614658d3-558f-4d77-849b-821112df27ee
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/privatednszones/virtualnetworklinks' | extend registrationEnabled = properties.registrationEnabled | extend compliant = iff(registrationEnabled == true, 1, 0) | project name, id, compliant
