// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 619e8a13-f988-4795-85d6-26886d70ba6c
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.insights/diagnosticsettings' | extend storageAccountId = tostring(properties.storageAccountId) | extend compliant = iff(isnotempty(storageAccountId), 1, 0) | project name, id, storageAccountId, compliant
