// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 667313b4-f566-44b5-b984-a859c773e7d2
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type == 'microsoft.management/managementgroups' | extend displayName = coalesce(tostring(properties.displayName), name), displayNameLower = tolower(displayName) | extend compliant = iff(displayNameLower has 'sandbox', 1, 0) | project name = displayName, id, compliant
