// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 669b215a-ce43-4371-8f6f-11047f6490f1
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/expressroutecircuits' | extend peeringLocation = tostring(properties.serviceProviderProperties.peeringLocation) | summarize circuitCount = count(), peeringLocations = dcount(peeringLocation), locations = make_set(peeringLocation) | extend compliant = iff(circuitCount >= 2 and peeringLocations >= 2, 1, 0) | project circuitCount, peeringLocations, locations, compliant
