// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 67e7a8ed-4b30-4e38-a3f2-9812b2363cef
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.operationalinsights/workspaces' | summarize workspaceCount = count(), regions = make_set(location) | extend compliant = iff(workspaceCount == 1, 1, 0) | project workspaceCount, regions, compliant
