// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 7025b442-f6e9-4af6-b11f-c9574916016f
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/expressroutecircuits' | extend skuFamily=tostring(sku.family) | extend bw=tostring(properties.bandwidthInMbps) | extend compliant = iff(skuFamily =~ 'MeteredData', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='ER Data Plan', currentValue=strcat(skuFamily, ', ', bw, ' Mbps'), expectedValue='MeteredData (unless unlimited needed)', compliant
