// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 718cb437-b060-2589-8856-2e93a5c6633b
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/expressroutecircuits' | extend tier = tostring(sku.tier) | extend compliant = iff(tier == 'Local', 1, 0) | project name, id, tier, compliant
