// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 72105cc8-aaea-4ee1-8c7a-ad25977afcaf
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand subnets=properties.subnets | where subnets.name =~ 'GatewaySubnet' | extend rtId=tostring(subnets.properties.routeTable.id) | extend hasRT = isnotempty(rtId) | project id, name, resourceGroup, subscriptionId, checkItem='GatewaySubnet Route Table', currentValue=iff(hasRT, tostring(split(rtId,'/')[-1]), 'No route table'), expectedValue='Ensure gateway route propagation correct', compliant=iff(hasRT, true, false)
