// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 727c77e1-b9aa-4a37-a024-129d042422c1
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualwans' | extend b2b=tostring(properties.allowBranchToBranchTraffic) | extend compliant = iff(b2b =~ 'true', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='VWAN Branch-to-Branch', currentValue=strcat('allowBranchToBranch: ', iff(isnotempty(b2b), b2b, 'Not set')), expectedValue='true', compliant
