// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 74d00018-ac6a-49e0-8e6a-83de5de32c19
// Vendored at: 2026-05-13T09:27:15+00:00
authorizationresources | where type =~ 'microsoft.authorization/roleassignments' | extend scope = tostring(properties.scope) | where scope startswith '/providers/Microsoft.Management/managementGroups' | extend principalType = tostring(properties.principalType) | summarize count() by principalType | project checkItem='MG Role Assignments', currentValue=strcat(principalType, ': ', tostring(count_)), expectedValue='Restricted to privileged groups', compliant=iff(principalType =~ 'Group', true, false)
