// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 77425f48-ecba-43a0-aeac-a3ac733ccc6a
// Vendored at: 2026-05-13T09:27:15+00:00
securityresources | where type == 'microsoft.security/pricings' | extend tier = tostring(properties.pricingTier) | extend compliant = iff(tier == 'Standard', 1, 0) | project name, id, compliant
