// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 78b22132-b41c-460b-a4d3-df8f73a67dc2
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend displayName = tolower(tostring(properties.displayName)), scope = tostring(properties.scope) | where displayName has 'global' or displayName has 'confidential' | extend compliant = iff(tolower(scope) has '/providers/microsoft.management/managementgroups/', 1, 0) | project name, id, scope, compliant
