// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 7d5d1e4e-6146-458d-9558-fd77249b8211
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualhubs' | extend fwId=tostring(properties.azureFirewall.id) | extend compliant = iff(isnotempty(fwId), true, false) | project id, name, resourceGroup, subscriptionId, checkItem='FW in Secured Hub', currentValue=iff(isnotempty(fwId), 'Secured', 'No firewall'), expectedValue='Azure Firewall deployed', compliant
