// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 7dd61623-a364-4a90-9eca-e48ebd54cd7d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type in~ ('microsoft.network/virtualnetworkgateways','microsoft.network/azurefirewalls','microsoft.network/dnsresolvers','microsoft.network/expressroutecircuits','microsoft.network/privatednszones') | extend compliant = 1 | project name, id, type, location, compliant
