// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 7ea02e1c-7166-45a3-bdf5-098891367fcb
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize recoveryVaults = countif(type == 'microsoft.recoveryservices/vaults'), replicationResources = countif(type has 'microsoft.recoveryservices/vaults/replication') | extend compliant = iff(recoveryVaults > 0 and replicationResources > 0, 1, 0) | project recoveryVaults, replicationResources, compliant
