// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 7f408960-c626-44cb-a018-347c8d790cdf
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.insights/diagnosticsettings' | extend lowerId = tolower(id), workspaceId = tostring(properties.workspaceId) | where (lowerId has '/microsoft.network/applicationgateways/' or lowerId has '/microsoft.cdn/profiles/' or lowerId has '/microsoft.network/frontdoors/') and isnotempty(workspaceId) | extend compliant = 1 | project name, id, workspaceId, compliant
