// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 859c3900-4514-41eb-b010-475d695abd74
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.insights/actiongroups' | extend enabled = tostring(properties.enabled) | project id, name, resourceGroup, subscriptionId, checkItem='Action Groups', currentValue=strcat('Enabled: ', enabled), expectedValue='Action groups configured for alerts', compliant=iff(enabled =~ 'true', true, false)
