// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 914b8cb7-c2f6-40fa-ae18-81c049e0cb5a
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type == 'microsoft.management/managementgroups' | extend displayName = tolower(coalesce(tostring(properties.displayName), name)) | extend compliant = iff(displayName in ('public','confidential corp','confidential online') or displayName has 'confidential corp' or displayName has 'confidential online', 1, 0) | project name = coalesce(tostring(properties.displayName), name), id, compliant
