// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 91b9d7d5-91e1-4dcb-8f1f-fa7e465646cc
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand subnets=properties.subnets | where subnets.name =~ 'RouteServerSubnet' | extend prefix=tostring(subnets.properties.addressPrefix) | extend prefixLen=toint(split(prefix, '/')[1]) | extend compliant = iff(prefixLen <= 27, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='RouteServer Subnet', currentValue=prefix, expectedValue='/27 or larger', compliant
