// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 94f3eede-9aa3-4088-92a3-bb9a56509fad
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/firewallpolicies' | where array_length(properties.firewalls) > 0 | extend dnsProxy = tostring(properties.dnsSettings.enableProxy) | extend compliant = iff(dnsProxy =~ 'true', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='DNS Proxy (attached)', currentValue=iff(isnotempty(dnsProxy), dnsProxy, 'Not configured'), expectedValue='true', compliant
