// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 97be9951-9048-4384-9c98-6cb2913156a1
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type in~ ('microsoft.insights/metricalerts','microsoft.insights/scheduledqueryrules','microsoft.insights/activitylogalerts') | extend compliant = 1 | project name, id, type, compliant
