// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 9c75dfef-573c-461c-a698-68598595581a
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualhubs' | extend addrPrefix=tostring(properties.addressPrefix) | extend prefixLen=toint(split(addrPrefix, '/')[1]) | extend compliant = iff(prefixLen <= 23, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Hub Address Space', currentValue=addrPrefix, expectedValue='/23 or larger', compliant
