// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: 9dcd6250-9c4a-4382-aa9b-5b84c64fc1fe
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/loadbalancers' | extend skuName=tostring(sku.name) | extend skuTier=tostring(sku.tier) | extend compliant = iff(skuName =~ 'Standard', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Standard LB SKU', currentValue=strcat('SKU: ', skuName, ', Tier: ', iff(isnotempty(skuTier), skuTier, 'N/A')), expectedValue='Standard', compliant
