// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a4d87397-48b6-462d-9d15-f512a65498f6
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/virtualnetworks' | mv-expand subnet = properties.subnets | extend subnetName = tostring(subnet.name), nsgId = tostring(subnet.properties.networkSecurityGroup.id) | extend compliant = iff(isnotempty(nsgId), 1, 0) | project name, id, subnetName, nsgId, compliant
