// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a52e0c98-76b9-4a09-a1c9-6b2babf22ac4
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | summarize subCount=count() | project checkItem='Subscription Count', currentValue=strcat(tostring(subCount), ' subscriptions'), expectedValue='Subscription vending automated', compliant=iff(subCount > 0, true, false)
