// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a56888b2-7e83-4404-bd31-b886528502d1
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.operationalinsights/workspaces' | extend retention=tostring(properties.retentionInDays) | extend skuName=tostring(properties.sku.name) | project id, name, resourceGroup, subscriptionId, checkItem='Log Analytics Workspace', currentValue=strcat('SKU: ', skuName, ', Retention: ', retention, ' days'), expectedValue='Centralized, 90+ days retention', compliant=iff(toint(retention) >= 90, true, false)
