// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a6e55d7d-8a2a-4db1-87d6-326af625ca44
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend displayName = tolower(tostring(properties.displayName)), definitionId = tolower(tostring(properties.policyDefinitionId)) | extend compliant = iff(displayName has 'deny' or definitionId has 'deny', 1, 0) | project name, id, compliant
