// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a89153d8-18b2-4caf-bc19-850fc8fba00f
// Vendored at: 2026-05-13T09:27:15+00:00
resources | extend dataClassification = coalesce(tostring(tags['DataClassification']), tostring(tags['dataClassification']), tostring(tags['Classification']), tostring(tags['classification'])) | extend compliant = iff(isnotempty(dataClassification), 1, 0) | project name, id, dataClassification, compliant
