// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: a9e65070-c59e-4112-8bf6-c11364d4a2a5
// Vendored at: 2026-05-13T09:27:15+00:00
authorizationresources | where type =~ 'microsoft.authorization/roledefinitions' | where properties.type =~ 'CustomRole' | extend roleName = tostring(properties.roleName) | project id, checkItem='Custom Workload Roles', currentValue=roleName, expectedValue='Custom roles for workload teams', compliant=true
