// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: aa45be6a-8f2d-4896-b0e3-775e6e94e610
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend displayName = tolower(tostring(properties.displayName)), definitionId = tolower(tostring(properties.policyDefinitionId)) | extend compliant = iff(displayName has 'monitor baseline alerts' or displayName has 'amba' or definitionId has 'monitor_baseline_alerts', 1, 0) | project name, id, compliant
