// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: b03ed428-4617-4067-a787-85468b9ccf3f
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.storage/storageaccounts' | extend httpsOnly = properties.supportsHttpsTrafficOnly | extend compliant = iff(httpsOnly == true, 1, 0) | project name, id, compliant
