// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: b3e4563a-4d87-4397-98b6-62d6d15f512a
// Vendored at: 2026-05-13T09:27:15+00:00
resources | summarize privateEndpoints = countif(type == 'microsoft.network/privateendpoints'), expressRouteCircuits = countif(type == 'microsoft.network/expressroutecircuits') | extend compliant = iff(privateEndpoints > 0 and expressRouteCircuits > 0, 1, 0) | project privateEndpoints, expressRouteCircuits, compliant
