// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: b9d0dff5-bdd4-4cd8-88ed-5811610b2b2c
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/firewallpolicies' | extend idpsMode = tostring(properties.intrusionDetection.mode) | extend compliant = iff(idpsMode =~ 'Deny', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='IDPS Mode', currentValue=iff(isnotempty(idpsMode), idpsMode, 'Not configured'), expectedValue='Deny', compliant
