// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: be7d7e48-4327-46d8-adc0-55bcf619e8a1
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend definitionId = tolower(tostring(properties.policyDefinitionId)) | extend compliant = iff(definitionId !has '/subscriptions/' and definitionId !has '/providers/microsoft.management/managementgroups/', 1, 0) | project name, id, compliant
