// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c10d51ef-f999-455d-bba0-5c90ece07447
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/firewallpolicies' | extend skuTier = tostring(properties.sku.tier) | extend compliant = iff(skuTier =~ 'Premium', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Firewall Premium SKU', currentValue=iff(isnotempty(skuTier), skuTier, 'Not configured'), expectedValue='Premium', compliant
