// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c2299c4d-7b57-4d0c-9555-62f2b3e4563a
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/connections' | extend connectionType = tostring(properties.connectionType), fastPath = properties.expressRouteGatewayBypass | where connectionType == 'ExpressRoute' | extend compliant = iff(fastPath == true, 1, 0) | project name, id, compliant
