// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c44c6f0e-1642-4a61-a17b-0922f835c93a
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/firewallpolicies/rulecollectiongroups' | mv-expand ruleCollection = properties.ruleCollections | mv-expand rule = ruleCollection.rules | where tolower(tostring(rule.ruleType)) == 'natrule' | extend sourceAddresses = tostring(rule.sourceAddresses) | extend compliant = iff(sourceAddresses has '"*"' or sourceAddresses has 'Any', 0, 1) | project name, id, compliant
