// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c68e1d76-6673-413b-9f56-64b5e984a859
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.capacity/reservationorders' | extend displayName = tostring(properties.displayName) | extend provState = tostring(properties.provisioningState) | extend compliant = iff(provState =~ 'Succeeded', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Reserved Instances', currentValue=strcat('Reservation: ', displayName, ', State: ', provState), expectedValue='Active reservations for cost optimization', compliant
