// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c76cb5a2-abe2-11ed-afa1-0242ac120002
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworks' | mv-expand peering=properties.virtualNetworkPeerings | extend allowAccess=tostring(peering.properties.allowVirtualNetworkAccess) | extend peerState=tostring(peering.properties.peeringState) | extend compliant = iff(allowAccess =~ 'true', true, false) | project id, name, resourceGroup, subscriptionId, peeringName=tostring(peering.name), checkItem='Peering Allow Traffic', currentValue=strcat('AllowAccess: ', allowAccess, ', State: ', peerState), expectedValue='true', compliant
