// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c773e7d2-6162-43a7-95a9-17e1f348ef25
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.portal/dashboards' or type =~ 'microsoft.insights/workbooks' | project id, name, resourceGroup, subscriptionId, type, checkItem='Monitoring Dashboards', currentValue=strcat(type, ': ', name), expectedValue='Dashboards for capacity monitoring', compliant=true
