// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: c806c048-26b7-4ddf-b4c2-b4f0c476925d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.maintenance/maintenanceconfigurations' | extend scope = tostring(properties.maintenanceScope) | extend recurEvery = tostring(properties.maintenanceWindow.recurEvery) | extend compliant = true | project id, name, resourceGroup, subscriptionId, checkItem='Update Manager Config', currentValue=strcat('Scope: ', scope, ', RecurEvery: ', recurEvery), expectedValue='Maintenance configuration exists', compliant
