// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: cacf55bc-e4e4-46be-96bc-57a5f23a269a
// Vendored at: 2026-05-13T09:27:15+00:00
resourcecontainers | where type =~ 'microsoft.resources/subscriptions' | project id, name, subscriptionId, checkItem='Subscription Naming', currentValue=name, expectedValue='Follows naming convention', compliant=true
