// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: cdb3751a-b2ab-413a-ba6e-55d7d8a2adb1
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.keyvault/vaults' | extend publicNetworkAccess = tostring(properties.publicNetworkAccess), defaultAction = tostring(properties.networkAcls.defaultAction), privateEndpointCount = toint(coalesce(array_length(properties.privateEndpointConnections), 0)) | extend compliant = iff(privateEndpointCount > 0 or publicNetworkAccess == 'Disabled' or defaultAction == 'Deny', 1, 0) | project name, id, privateEndpointCount, publicNetworkAccess, defaultAction, compliant
