// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: d38ad60c-bc9e-4d49-b699-97e5d4dcf707
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/azurefirewalls' | extend zoneCount = array_length(zones) | extend compliant = iff(zoneCount > 1, true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Multi-AZ Deployment', currentValue=iff(zoneCount > 0, strcat(tostring(zoneCount), ' zones: ', tostring(zones)), 'No zones'), expectedValue='Multiple AZs', compliant
