// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: d49ac006-6670-4bc9-9948-d3e0a3a94f4d
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualhubs' | extend routingPref=tostring(properties.hubRoutingPreference) | extend compliant = iff(routingPref =~ 'ASPath', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Hub Routing Preference', currentValue=iff(isnotempty(routingPref), routingPref, 'Not configured'), expectedValue='ASPath', compliant
