// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: d4cd21b0-8813-47f5-b6c4-cfd3e504547c
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/virtualnetworkgateways' | where properties.gatewayType =~ 'vpn' or properties.gatewayType =~ 'ExpressRoute' | extend skuName=tostring(properties.sku.name) | extend skuTier=tostring(properties.sku.tier) | extend gwType=tostring(properties.gatewayType) | extend compliant = iff(skuTier !in~ ('Basic','Standard'), true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Gateway SKU', currentValue=strcat(gwType, ': ', skuName), expectedValue='Not Basic/Standard', compliant
