// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: d8a2adb1-17d6-4326-af62-5ca44e5695f2
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type =~ 'microsoft.authorization/policyassignments' | extend displayName = tostring(properties.displayName) | extend enforcementMode = tostring(properties.enforcementMode) | extend scope = tostring(properties.scope) | project id, name=displayName, checkItem='Policy Assignments', currentValue=strcat(displayName, ' (', enforcementMode, ') at ', scope), expectedValue='Policies aligned to compliance requirements', compliant=iff(enforcementMode =~ 'Default', true, false)
