// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: d98d954d-7d1c-4a07-92a7-cf3afe8dcbd2
// Vendored at: 2026-05-13T09:27:15+00:00
authorizationresources | where type =~ 'microsoft.authorization/roleassignments' | extend roleId = tostring(properties.roleDefinitionId) | extend principalType = tostring(properties.principalType) | where roleId endswith '8e3af657-a8ff-443c-a75c-2fe8c4bcb635' | summarize ownerCount=count() | project checkItem='Owner Role Count', currentValue=strcat(tostring(ownerCount), ' Owner assignments'), expectedValue='Minimize - use least privilege', compliant=iff(ownerCount <= 10, true, false)
