// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: da6e55d7-d8a2-4adb-817d-6326af625ca4
// Vendored at: 2026-05-13T09:27:15+00:00
policyresources | where type == 'microsoft.authorization/policyassignments' | extend displayName = tolower(tostring(properties.displayName)), definitionId = tolower(tostring(properties.policyDefinitionId)) | extend compliant = iff(displayName has 'machine configuration' or displayName has 'guest configuration' or definitionId has 'guestconfiguration' or definitionId has 'machineconfiguration', 1, 0) | project name, id, compliant
