// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: dfe237de-143b-416c-91d7-aa9b64704489
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/networkwatchers/flowlogs' | extend enabled=tostring(properties.enabled) | extend ta=tostring(properties.flowAnalyticsConfiguration.networkWatcherFlowAnalyticsConfiguration.enabled) | extend compliant = iff(enabled =~ 'true' and ta =~ 'true', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Flow Logs + Traffic Analytics', currentValue=strcat('Enabled: ', enabled, ', TrafficAnalytics: ', iff(isnotempty(ta), ta, 'N/A')), expectedValue='Both enabled', compliant
