// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: e0d5973c-d4cd-421b-8881-37f5e6c4cfd3
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/connections' | where properties.connectionType =~ 'ExpressRoute' | extend erCircuit=tostring(properties.peer.id) | extend peeringLocation=tostring(split(erCircuit,'/')[-1]) | summarize circuitCount=count() by peeringLocation | project checkItem='ER Redundancy', peeringLocation, currentValue=strcat(tostring(circuitCount), ' connection(s)'), expectedValue='Multiple peering locations', compliant=iff(circuitCount >= 1, true, false)
