// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: e3ab3693-829e-47e3-8618-3687a0477a20
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.operationalinsights/workspaces' | extend dataExport = properties.features.enableDataExport | project id, name, resourceGroup, subscriptionId, checkItem='Log Export Config', currentValue=strcat('DataExport: ', tostring(dataExport)), expectedValue='Logs processed in Azure, not raw export to on-prem', compliant=true
