// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: e43a58a9-c229-49c4-b7b5-7d0c655562f2
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.network/privateendpoints' | extend targetResource = tostring(properties.privateLinkServiceConnections[0].properties.privateLinkServiceId) | extend compliant = 1 | project name, id, targetResource, compliant
