// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: e5f8d79f-2e87-4768-924c-516775c6ea95
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type == 'microsoft.insights/diagnosticsettings' | extend workspaceId = tostring(properties.workspaceId) | extend compliant = iff(isnotempty(workspaceId), 1, 0) | project name, id, workspaceId, compliant
