// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: e9c8f584-6d5e-473b-8dc5-acc9fbaab4e3
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/firewallpolicies' | extend threatIntelMode = tostring(properties.threatIntelMode) | extend compliant = iff(threatIntelMode =~ 'Deny', true, false) | project id, name, resourceGroup, subscriptionId, checkItem='Threat Intel Mode', currentValue=iff(isnotempty(threatIntelMode), threatIntelMode, 'Not configured'), expectedValue='Deny', compliant
