// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: f4e7926a-ec35-476e-a412-5dd17136bd62
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type =~ 'microsoft.network/connections' | where properties.connectionType =~ 'ExpressRoute' | extend erCircuit=tostring(properties.peer.id) | project id, name, resourceGroup, subscriptionId, checkItem='ER Connection', currentValue=strcat('Circuit: ', tostring(split(erCircuit,'/')[-1])), expectedValue='Local SKU where applicable', compliant=true
