// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: f5664b5e-984a-4859-a773-e7d261623a76
// Vendored at: 2026-05-13T09:27:15+00:00
authorizationresources | where type =~ 'microsoft.authorization/roledefinitions' | where properties.type =~ 'CustomRole' | project id, name=tostring(properties.roleName), checkItem='Custom RBAC Roles', currentValue=tostring(properties.roleName), expectedValue='Custom roles for key functions', compliant=true
