// Vendored from https://github.com/martinopedal/alz-checklist-queries/blob/e7641beeda0126cc78825f8b77764c379552f3e1/queries/alz_all_queries.json
// Source checklist ID: f625ca44-e569-45f2-823a-ce8cb12308ca
// Vendored at: 2026-05-13T09:27:15+00:00
resources | where type in~ ('microsoft.recoveryservices/vaults','microsoft.dataprotection/backupvaults') | extend compliant = 1 | project name, id, type, compliant
