name: dependency-review

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.5.0
        with:
          fail-on-severity: high
